### ISSUE TITLE
Is the profiles supabase call authenticated?

### ISSUE THREAD

**Issue by jca41** [one-aalam/remix-starter-kit#1]
First of all, nice work! 😊

I have a Q around authenticated queries to be used with supabase policies.

Is your profiles call to supabase an authenticated request? If so, how do you make it work?

**Comment by one-aalam** [comment]
Thanks @jca41 Glad you liked it.

Yes, the profiles call is an authenticated request. Authentication detail is persisted in the browser's cookie [here](https://github.com/one-aalam/remix-starter-kit/blob/main/app/routes/auth.tsx#L57) and later used to authenticate and let the user go to profile or redirect back to the auth page [here](https://github.com/one-aalam/remix-starter-kit/blob/main/app/routes/profile.tsx#L14). 

As far as the autogenerated `from` CRUD API calls are considered they work in the context of the currently logged in user, which the CRUD APIs gather internally, and get it as long as the user is not [logged out](https://github.com/one-aalam/remix-starter-kit/blob/main/app/routes/signout.tsx#L9).

Hope, this answers your query?

**Comment by jca41** [comment]
Great thanks!

**Comment by jca41** [comment]
Was reading the supabase docs and I think maybe you could use the `setAuth` method.
This way the supabase client is able to send requests authenticated as the user.

https://supabase.com/docs/reference/javascript/auth-setauth
