### ISSUE TITLE
Auth with providers (e.g. Google/GitHub)

### ISSUE THREAD

**Issue by bernatfortet** [one-aalam/remix-starter-kit#2]
What would need to change to login with an oAuth provider, e.g. Google/GitHub?

**Comment by one-aalam** [comment]
Hey @bernatfortet this starter kit is [Supabase](https://supabase.io/) focussed. If you want to use any of the oAuth providers listed [here](https://supabase.com/docs/guides/auth) you can follow any of the guides mentioned in the Supabase docs like [Google](https://supabase.com/docs/guides/auth/auth-google) or [Github](https://supabase.com/docs/guides/auth/auth-github), and introduce a button, somewhere in the [AuthForm](https://github.com/one-aalam/remix-starter-kit/blob/main/app/components/AuthForm.tsx) component, or the [Auth](https://github.com/one-aalam/remix-starter-kit/blob/main/app/routes/__auth/auth.tsx) page and call 
```js
const { user, session, error } = await supabase.auth.signIn({
  provider: 'github', // or, google
})
```

**Comment by bernatfortet** [comment]
Thanks 👍
