### ISSUE TITLE
Example app is down

### ISSUE THREAD

**Issue by noahpryor** [one-aalam/remix-starter-kit#7]
### Describe the bug

Example site is throwing a 500

### Your Example Website or App

https://remix-starter-kit.vercel.app/

### Steps to Reproduce the Bug or Issue

1. Go to https://remix-starter-kit.vercel.app/
2. See the 500 error

### Expected behavior

To see the example 

### Platform

- OS: iOS 
- Browser: safari
- Version: [e.g. 91.1]

**Comment by one-aalam** [comment]
Hey @noahpryor please clone the project/use the template and configure `SUPABASE_URL` and `SUPABASE_KEY` with your development and it should work for you. `SUPABASE_URL` and `SUPABASE_KEY` are exposed to the client for few internal routes, and thus are not available in the demo app's settings.

For a quick view of how things look when deployed, you can refer the screenshots in the README
